### ISSUE TITLE
Index Pattern Incorrect

### ISSUE THREAD

**Issue by dajs3010** [PhaedrusTheGreek/transform_vis#11]
Hi guys I have builded this plugin for kibana 5.6 version, but when I'm trying to get it work, I can see that the index patterns are showing as id's and not by their names, and when I'm trying to execute it I'm getting an Elasticsearch error. Also the javascript section is not showing

![captura de pantalla 2017-09-20 a las 16 50 05](https://user-images.githubusercontent.com/16548843/30669511-37fcf7a0-9e24-11e7-8eb0-dd19e9e548db.png)

**Comment by PhaedrusTheGreek** [comment]
This was fixed with the updates for 5.6.0
