### ISSUE TITLE
How about a plan for Kibana 6.0.0 ?

### ISSUE THREAD

**Issue by bienxanhst7** [PhaedrusTheGreek/transform_vis#12]
Thank you so much for this awesome plugin. 

It's really helpful for our team in many use cases. We are testing Kibana 6.0.0 rc and would like to upgrade our Kibana from 5.x to 6.0.0 right after an official release.
We'd appreciate it if you could share a plan for 6.0.0 or 6.x.

**Comment by PhaedrusTheGreek** [comment]
Sure, I will look into preparing a 6.x compatible build before GA.

**Comment by PhaedrusTheGreek** [comment]
Transform Vis 6.0.0 is live
