### ISSUE TITLE
Support for Kibana 5.6.2

### ISSUE THREAD

**Issue by keeshqs** [PhaedrusTheGreek/transform_vis#13]
This plugin would help in the development of our kibana dashboard in many ways and currently we're using version 5.6.2  and we cannot downgrade our system due to other plugin incompatibility.  We would truly appreciate if you could help us  and share if you have plans on supporting latest releases of Kibana (specifically 5.6.2). Thank you so much in advance!

Regards,
Keeshia

**Comment by keeshqs** [comment]
![image](https://user-images.githubusercontent.com/26063544/31584676-7896febc-b1e5-11e7-9628-482fa9b52dac.png)

![image](https://user-images.githubusercontent.com/26063544/31584699-b73e0b38-b1e5-11e7-8a2f-506c7f346cf7.png)

I was able to install it but there's no javascript. Only DSL and Template., 
Please advise.

**Comment by PhaedrusTheGreek** [comment]
Support for 5.6.4 is live
