### ISSUE TITLE
Can not see JS input window

### ISSUE THREAD

**Issue by YanekR** [PhaedrusTheGreek/transform_vis#16]
HI, 

After installation of plugin, the JS minput window is not visible, could you please assist?

Thanks,
Jan

<img width="352" alt="zrzut ekranu 2018-02-14 o 14 37 51" src="https://user-images.githubusercontent.com/10604141/36207000-b85164f2-1194-11e8-910d-a2073700a4fb.png">

**Comment by PhaedrusTheGreek** [comment]
[In order to use JS, you have to enable it](https://github.com/PhaedrusTheGreek/transform_vis#support-for-javascript) in order to consent to any security issue that might arise.

```
transform_vis.allow_unsafe: true
```

**Comment by YanekR** [comment]
Thank you, for your help. 
All works perfectly. 

Thanks,
Janek
