### ISSUE TITLE
Possibility of using style-tags

### ISSUE THREAD

**Issue by ghost** [PhaedrusTheGreek/transform_vis#2]
Hey, 
first let me thank you for the awesome plugin.

Is there a possibility to use CSS for styling the template? A symple <style> tag is not working properly.

Thanks

**Comment by PhaedrusTheGreek** [comment]
I just pushed some changes that will allow this.  requires `transform_vis.allow_unsafe`

Example:
```
<style>
.my_font {
  font-size: 100px;
}
</style>
<div class="my_font">Test<div>
```

**Comment by ghost** [comment]
Awesome. This makes this plugin to a perfect addition for it-internal dashboards! Thank you.
