### ISSUE TITLE
6.4.0 No index pattern

### ISSUE THREAD

**Issue by nickerber** [PhaedrusTheGreek/transform_vis#20]
I see, you just updated to 6.4.0 a few days ago and didn't tag it yet..

when I download and install commit e4b62ffdbdfe0251f9597e12803f4d3be834d60c in version 6.4.0 I am not able to save the index pattern. All index patterns are showing correctly in the dropdown-menu but as far as I choose one the visualization window says "No Index Pattern". Same message for all already existing transform-visualizations.

Any suggestions?
![image](https://user-images.githubusercontent.com/29973558/44791288-8ee11480-aba1-11e8-91e8-52cf2074b4ba.png)
![image](https://user-images.githubusercontent.com/29973558/44791316-9dc7c700-aba1-11e8-9292-1196b2191c36.png)

**Comment by PhaedrusTheGreek** [comment]
Confirmed - very strange as I tested this working a few days before 6.4.0 was released.   I'll review and come up with a fix shortly.

**Comment by PhaedrusTheGreek** [comment]
This should be resolved with the `editorState` changes [described here](https://www.elastic.co/blog/upcoming-kibana-plugin-api-changes-in-6-4).  The 6.4.0 release zip is in place now - let me know if it's working for you.

**Comment by nickerber** [comment]
Works now, perfect! Thanks for your fast help and this awesome plugin.
