### ISSUE TITLE
Can one perform queries on multiple indices with this plugin?

### ISSUE THREAD

**Issue by digitalrinaldo** [PhaedrusTheGreek/transform_vis#5]
I would like to create visualizations using data from different indices. Is that possible directly or do I need to use jquery and perform ajax calls?  Thanks for the super useful plugin.

Is there anyway to have user input with this plugin?

**Comment by PhaedrusTheGreek** [comment]
When selecting a Kibana index pattern, you can choose an index pattern containing multiple indices.  We suggest that indices that are queryable together should be named with a common prefix like `logs-<app>-*`  that way if you want to query all logs, you can create an index pattern called `logs-*`
