### ISSUE TITLE
Kibana 5.4.1

### ISSUE THREAD

**Issue by ricardoatsouza** [PhaedrusTheGreek/transform_vis#6]
Any plans to make a release for Kibana 5.4.1?

**Comment by thekofimensah** [comment]
Or 5.4.3? :D

**Comment by PhaedrusTheGreek** [comment]
Often between minor/maintenance versions, you can just open up the plugin zip file, modify `package.json` to set the version numbers to your current Kibana version.

I've taken 5.3.0-2 and modified it for 5.4.3 and tested, and it seems good, so I'll attach here:

[transform_vis-5.4.3.zip](https://github.com/PhaedrusTheGreek/transform_vis/files/1484739/transform_vis-5.4.3.zip)

To support 5.4.1, just open up this zip and modify it accordingly.
