### ISSUE TITLE
Can we pass the output of the query/ JS/ template to an existing visual

### ISSUE THREAD

**Issue by evanceheallyg** [PhaedrusTheGreek/transform_vis#8]
Can we pass the output of the query/ JS/ template to an existing visual. Since we don't want to recreate all the existing visuals embedded as html/JS in Template section. Since I am not well versed in JS, please forgive if its a stupid question.

P.S 
Thank you so much for the widget/ help you are providing.

**Comment by PhaedrusTheGreek** [comment]
Not currently possible, but I believe that this type of thing will be in Kibana's future somehow.   

In the meantime, check out [vega-vis](https://github.com/nyurik/kibana-vega-vis)

**Comment by evanceheallyg** [comment]
Thank you so much Phaedrus. We are in Kibana 5.4 and looks like vega is not compatible. So we did a upgrade to 5.5 and time widget went off :). We are exploring the tool and looks like this could save us at this point of time. Thanks again.

P.S

One clarification: Apart from the @timestamp : %timefilter% in vega, is there a possibility to add dashboard context similar to transform_vis - _DASHBOARD_CONTEXT_?

**Comment by evanceheallyg** [comment]
Hello @PhaedrusTheGreek, I got an update from @nyurik that as of now its not possible but he is working on it and would be available shortly. Thanks for all the support.
